### ISSUE TITLE
Issue Opening new tab on Linux

### ISSUE THREAD

**Issue by Bobfritguy** [HDLGen-ChatGPT/HDLGen-ChatGPT#48]
#### Description:
Errors returned when switching tabs in Linux

#### Steps to Reproduce
1. Open HDLGen, `python main.py`
2. Click "Create new project"
3. Click "HDL Designer"

#### Expected Behaviour
Switch Tabs

#### Actual Behaviour
Switches Tabs, produces error

>Traceback (most recent call last):
  File "/home/seamus/Xilinx/HDLGen/HDLGen-ChatGPT/Application/Home/home.py", line 633, in handle_tab_change
    self.hdl_designer.architecture.save_data()
  File "/home/seamus/Xilinx/HDLGen/HDLGen-ChatGPT/Application/HDLDesigner/Architecture/architecture.py", line 479, in save_data
    self.generator.generate_mainPackage()
  File "/home/seamus/Xilinx/HDLGen/HDLGen-ChatGPT/Application/Generator/generator.py", line 1430, in generate_mainPackage
    root = minidom.parse(mainPackageDir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xml/dom/minidom.py", line 1990, in parse
    return expatbuilder.parse(file)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xml/dom/expatbuilder.py", line 910, in parse
    with open(file, 'rb') as fp:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/seamus/Xilinx/HDLGen/HDLGen-ChatGPT/User_Projects/Package/mainPackage.hdlgen'

#### Environment Details:
- Operating System: Arch Linux x86_64
- Python Version: Python 3.11.5
- Package Versions:
  - Markdown 3.4.4
  - PySide2 5.15.10
  - QtAwesome 1.2.3
  - pyperclip 1.8.2

#### Additional Information
Full output from start to finish

> [user@laptop]$ python main.py
>Setting up UI
Saving project details at  /home/seamus/Xilinx/HDLGen/HDLGen-ChatGPT/User_Projects/Untitled/HDLGenPrj
/home/seamus/Xilinx/HDLGen/HDLGen-ChatGPT/User_Projects
>Successfully saved!
>
>
>Saved Component details
Saved Component details
Saved port signal
>Traceback (most recent call last):
  File "/home/seamus/Xilinx/HDLGen/HDLGen-ChatGPT/Application/Home/home.py", line 633, in handle_tab_change
    self.hdl_designer.architecture.save_data()
  File "/home/seamus/Xilinx/HDLGen/HDLGen-ChatGPT/Application/HDLDesigner/Architecture/architecture.py", line 479, in save_data
    self.generator.generate_mainPackage()
  File "/home/seamus/Xilinx/HDLGen/HDLGen-ChatGPT/Application/Generator/generator.py", line 1430, in generate_mainPackage
    root = minidom.parse(mainPackageDir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xml/dom/minidom.py", line 1990, in parse
    return expatbuilder.parse(file)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xml/dom/expatbuilder.py", line 910, in parse
    with open(file, 'rb') as fp:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/seamus/Xilinx/HDLGen/HDLGen-ChatGPT/User_Projects/Package/mainPackage.hdlgen'

**Comment by Daxorinator** [comment]
Possibly resolved by #50 if you want to pull down that patch and try it.
