### ISSUE TITLE
Package/mainPackage.hdlgen not generated if missing

### ISSUE THREAD

**Issue by Daxorinator** [HDLGen-ChatGPT/HDLGen-ChatGPT#50]
If `Package/mainPackage.hdlgen` is missing, HDLGen-ChatGPT throws an error and does not generate the missing file. If this file is missing it should be populated automatically.

Simply adding the file (e.g by using `touch` on Linux), doesn't resolve the issue.
Instead a new error is thrown:
```
Traceback (most recent call last):
  File "/home/crash/HDLGen-ChatGPT/Application/Home/home.py", line 633, in handle_tab_change
    self.hdl_designer.architecture.save_data()
  File "/home/crash/HDLGen-ChatGPT/Application/HDLDesigner/Architecture/architecture.py", line 479, in save_data
    self.generator.generate_mainPackage()
  File "/home/crash/HDLGen-ChatGPT/Application/Generator/generator.py", line 1433, in generate_mainPackage
    root = minidom.parse(mainPackageDir)
  File "/home/crash/.pyenv/versions/3.10.11/lib/python3.10/xml/dom/minidom.py", line 1990, in parse
    return expatbuilder.parse(file)
  File "/home/crash/.pyenv/versions/3.10.11/lib/python3.10/xml/dom/expatbuilder.py", line 911, in parse
    result = builder.parseFile(fp)
  File "/home/crash/.pyenv/versions/3.10.11/lib/python3.10/xml/dom/expatbuilder.py", line 211, in parseFile
    parser.Parse(b"", True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0
```

**Comment by Daxorinator** [comment]
Was forced to fix this before I could address #49 because it kept breaking my development environment.
Patch to come.
