### ISSUE TITLE
Issue with non-ASCII characters in usernames e.g, Seán

### ISSUE THREAD

**Issue by Daxorinator** [HDLGen-ChatGPT/HDLGen-ChatGPT#57]
Setting up UI
Project Closed!
Loading project from  C:/Users/FEARG/Downloads/maxByteWord0_new/maxByteWord0_second/HDLGenPrj/maxByteWord0_second.hdlgen
Loading project from  C:/Users/FEARG/Downloads/maxByteWord0_new/maxByteWord0_second/HDLGenPrj/maxByteWord0_second.hdlgen
Traceback (most recent call last):
  File "C:\2023\HDLGenTop\HDLGen-ChatGPT\Application\..\Application\main.py", line 183, in open_project
    self.window = Home(self.load_proj_dir)
  File "C:\2023\HDLGenTop\HDLGen-ChatGPT\Application\Home\home.py", line 51, in __init__
    self.project_manager = ProjectManager(self.proj_dir, self)
  File "C:\2023\HDLGenTop\HDLGen-ChatGPT\Application\ProjectManager\project_manager.py", line 248, in __init__
    self.load_proj_data(proj_dir)
  File "C:\2023\HDLGenTop\HDLGen-ChatGPT\Application\ProjectManager\project_manager.py", line 810, in load_proj_data
    data = minidom.parse(load_proj_dir[0])
  File "C:\Users\FEARG\AppData\Local\Programs\Python\Python310\lib\xml\dom\minidom.py", line 1990, in parse
    return expatbuilder.parse(file)
  File "C:\Users\FEARG\AppData\Local\Programs\Python\Python310\lib\xml\dom\expatbuilder.py", line 911, in parse
    result = builder.parseFile(fp)
  File "C:\Users\FEARG\AppData\Local\Programs\Python\Python310\lib\xml\dom\expatbuilder.py", line 207, in parseFile
    parser.Parse(buffer, False)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 69, column 14

**Comment by Daxorinator** [comment]
#64

**Comment by Daxorinator** [comment]
Needs a quick retest on Windows and Linux

**Comment by Daxorinator** [comment]
Fixed by #77
